apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec: # specification of deployment
  replicas: 2
  selector: 
    matchLabels:
      app: server
  template:
    metadata:
      name: server-pod
      labels:
        app: server
    spec: # spec of pod
      containers:
        - name: server
          image: vitak03/app1:firsstry

---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002
  
