apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: podman
      image: mgoltzsche/podman
      command: ["tail", "-f", "/dev/null"]      
      imagePullPolicy: Always
